config/routes.rb
Pingpong::Application.routes.draw do
  resources :players
  resources :games
  get "games/archive"
  match "/archive/:page" => "games#archive", :via => :get
  match "/archive" => "games#archive", :via => :get
  match "/players/:id" => "players#show", :via => :get
  root :to => "players#index", :id => 'index'
  match "players/add" => "players#add", :via => :post
  match "games/add" => "games#add", :via => :post

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  validate :challenger_played_in_game, :unique_players
  validates :winner, :presence => true
  validates :loser, :presence => true
  validates :winner_score, :numericality => { :greater_than_or_equal_to => 0 }
  validates :loser_score, :numericality=> { :greater_than_or_equal_to => 0 }
	belongs_to :winner, :class_name => "Player"
	belongs_to :loser, :class_name => "Player"
	belongs_to :challenger, :class_name => "Player"

  def challenger_played_in_game
    if(self.winner_id != self.challenger_id and self.loser_id != self.challenger_id)
        errors.add(:challenger_id, "must have played in game")
    end
  end

  def unique_players
    if(self.winner_id == self.loser_id)
      errors.add(:base, "Player cannot play themselves")
    end
  end

  default_scope order("games.created_at DESC")
end

app/models/player.rb
class Player < ActiveRecord::Base
	before_validation :humanize_name

	validates :name, :presence => true, :uniqueness => true, :case_sensitive => false, :length => { :maximum => 15 }
	has_many :wins, :class_name => "Game", :foreign_key => "winner_id"
	has_many :lose, :class_name => "Game", :foreign_key => "loser_id"
	has_many :challenges, :class_name => "Game", :foreign_key => "challenger_id"

	def games
		wins.count + lose.count
	end

	def get_elo
		return self.elo
	end

	def update_weight
		if(games <= 15)
			self.update_attribute(:weight, 70)
		elsif(15< games and games <= 30)
			self.update_attribute(:weight, 50)
		else
			self.update_attribute(:weight, 35)
		end
	end

	def update_elo(p2_elo, result)
		p1_elo = self.elo
		change = 0
		expected_score = (1.0 + (10 ** ((p2_elo - p1_elo)/400.0))) ** -1
		change = (self.weight * (result - expected_score)).round.to_int
		p1_elo += change
		self.update_attribute(:elo, p1_elo)
		return change
	end

	def humanize_name
		self.name = self.name.to_s.humanize
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def archive
    @games_items = Game.all.paginate(:page => params[:page], per_page: 14)
  end
  
  def index
  	@games_items = Game.all
  end 

  def create
    @game = Game.new(game_params)
    # @game = Game.create(:winner_id => params[:p1_id], :loser_id => params[:p2_id], 
      # :winner_score => params[:wscore], :loser_score => params[:lscore], 
      # :challenger_id => params[:ch_id])

    if @game.save
      @p1 = Player.find(game_params[:winner_id])
      @p2 = Player.find(game_params[:loser_id])
      p1_temp_elo = @p1.get_elo()
      p2_temp_elo = @p2.get_elo()
      @p1.update_weight()
      @p2.update_weight()
      p1_change = @p1.update_elo(p2_temp_elo, 1)
      p2_change = @p2.update_elo(p1_temp_elo, 0)
      @game.update_attribute(:p1_change, p1_change)
      @game.update_attribute(:p2_change, p2_change)
      flash[:notice] = "Game added"
      redirect_to games_path
    else
      redirect_to games_path, :notice => "Oops, try again. Errors: #{@game.errors.full_messages}"
    end
  end


  def destroy
    @game = Game.find(params[:id])
  	p1 = Player.find(@game.winner_id)
    p2 = Player.find(@game.loser_id)
    p1.update_attribute(:elo, p1.get_elo() - @game.p1_change)
    p2.update_attribute(:elo, p2.get_elo() - @game.p2_change)
    @game.destroy()
    flash[:notice] = "Game deleted"
  	redirect_to :action => 'index'
  end

  private 

    def game_params
      params.require(:game).permit(:winner_id, :loser_id, :winner_score, :loser_score, :challenger_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players_items = Player.all.sort{|y,x| x.get_elo() <=> y.get_elo()}
  end

  # def new
  #   @player = Player.new(params[:name].to_s.humanize)
  # end

  def create
    @player = Player.new(player_params)
    # @player = Player.create(params[:player])
  	# @player = Player.create(:name => params[:name].to_s.humanize, :elo_change => 0)

    if @player.save
      flash[:notice] = "Player " + player_params[:name].to_s.humanize + " added"
      redirect_to root_path
    else
      redirect_to root_path, notice: "Oops, try again. Errors: #{@player.errors.full_messages}"
    end
  end

  def show
  	@player = Player.find(params[:id])
  	@wins = @player.wins
  	@losses = @player.lose
  	@player_games = @wins + @losses
  end

  private 

    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper

end

app/views/games/archive.html.erb
<title>ID.me PingPong Tracker</title>
<br>

	<div class="left_head">
			<p class="text_header">All Games</p>
	</div>
	<div class = "right_head">
		<%= link_to "Add A Game", games_path %>
	</div>
	<br>
<div class="full_holder">
<table border = "1" class="table" style="text-align: center;">
			<tr>
				<th>Date</th>
				<th>Winner</th>
				<th>Loser</th>
				<th>Score</th>
				<th>Challenger</th>
				<th>Delete Game</th>
			</tr>
			<% @games_items.each do |t| %>
				<tr>
					<td><%= t.created_at.to_date %></td>
					<td><%= link_to t.winner.name, player_url(t.winner_id) %>
							<% if t.challenger.name == t.winner.name %>
							 (C)
							<% end %>
					</td>
					<td><%= link_to t.loser.name, player_url(t.loser_id) %>
							<% if t.challenger.name == t.loser.name %>
							 (C)
							<% end %>
					</td>
					<td><%= t.winner_score %> - <%= t.loser_score %></td>
					<td>
						<div id="parent">
							<div class="red right_hidden">▼<%= t.p2_change %></div>
							<div class="green left_hidden">▲<%= t.p1_change %></div>
						</div>
					</td>
					<td><%= link_to 'Delete', game_path(t.id), :method => :delete%></td>
				</tr>
			<% end %>
		</table>
		<%= will_paginate @games_items %>
	</div>
</div>

app/views/games/index.html.erb
<title>ID.me PingPong Tracker</title>
<br>

<div class="games_holder_r">
	<div class="left_head">
			<p class="text_header">Recent Games</p>
			<br>
			<% flash.each do |name, msg| -%>
				<div class="blue"><%= msg %></div>
			<% end %>
			<br>
	</div>

	<div class = "right_head">
		<%= link_to "See All Games", "archive" %>
	</div>
	<br>

	<div class="left">
		<table border = "1" class="table" style="text-align: center;">
			<tr>
				<th>Date</th>
				<th>Winner</th>
				<th>Loser</th>
				<th>Score</th>
				<th style="width:100px">Change</th>
				<th style="width:50px">Delete</th>
			</tr>

			<% @games_items.each_with_index do |t, index| %>
				<tr>
					<td><%= t.created_at.to_date %></td>
					<td><%= link_to t.winner.name, player_url(t.winner_id) %>
							<% if t.challenger.name == t.winner.name %>
							 (C)
							<% end %>
					</td>
					<td><%= link_to t.loser.name, player_url(t.loser_id) %>
							<% if t.challenger.name == t.loser.name %>
							 (C)
							<% end %>
					</td>
					<td><%= t.winner_score %> - <%= t.loser_score %></td>
					<td>
						<div id="parent">
							<div class="red right_hidden">▼<%= t.p2_change %></div>
							<div class="green left_hidden">▲<%= t.p1_change %></div>
						</div>
					</td>
					<td><%= link_to 'Delete', game_path(t.id), :method => :delete%></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

<div class="games_holder_l">
	<div class="center">
		<br><br><br><br>
		<%= form_for Game.create do |form| %>
			<%= form.label :winner_id %>
			<%= form.select :winner_id, options_for_select(Player.all.collect {|p| [p.name, p.id]}), { prompt: 'Please select a player'} %>
			<br>
			<%= form.label :loser_id %>
			<%= form.select :loser_id, options_for_select(Player.all.collect {|p| [p.name, p.id]}), { prompt: 'Please select a player'} %>
			<br>
			<%= form.label :challenger_id %>
			<%= form.select :challenger_id, options_for_select(Player.all.collect {|p| [p.name, p.id]}), { prompt: 'Please select a player'} %>
			<br>
			<%= form.label :winner_score %>
			<%= form.text_field :winner_score, placeholder: "Enter the winner's score" %>
			<%= form.label :loser_score %>
			<%= form.text_field :loser_score, placeholder: "Enter the loser's score" %>
			<%= form.submit("Add game", :class => "btn btn-primary")%>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    PingPong Rails App by Michael Liu and Matthew Jiang
  </small>
  <nav>
    <ul>
      <li><a href="https://github.com/troopswap/ping-pong-leaderboard">Github Documentation</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ID.me PingPong Leaderboard", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to 'Players', root_path %></li>
          <li><%= link_to 'Games', games_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pingpong</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/players/index.html.erb
<title>ID.me PingPong Tracker</title>
<br>

<div class="left_holder">
	<div class="center">
		<p class="text_header">All Players</p>
		<p class="blue">Note: Ranking table now sorts based on ELO</p>
		<% flash.each do |name, msg| %>
			<div class="blue"><%= msg %></div>
		<% end %>
	</div>
	<br>

	<div class="left">
		<table border = "1" class="table" style="text-align: center;">
			<tr>
				<th>Rank</th>
				<th>Name</th>
				<th>ELO</th>
				<th>Win Count</th>
				<th>Lose Count</th>
				<th>Challenges Sent</th>
			</tr>
			
			<% @players_items.each_with_index do |t, index| %>
				<tr>
					<td><%= index+1 %></td>
					<td><%= link_to t.name, player_url(t.id) %></td>
					<td><%= t.elo %></td>
					<td><%= t.wins.count %></td>
					<td><%= t.lose.count %></td>
					<td><%= t.challenges.count %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

<div class="right_holder">
	<div class="center">
		<br><br><br><br>	
		<%= form_for Player.create do |form| %>
		<%# form_tag("/players/add", :method => "post") do %>
		<%= form.label :name %>
		<%= form.text_field :name, placeholder: "Enter a player name" %>
		<%= form.submit("Add player", :class => "btn btn-primary") %>
		<% end %>
	</div>
</div>

app/views/players/show.html.erb
<title>ID.me PingPong Tracker</title>

<br>

<div class = "games_holder_l">
	<div class = "full_head">
		<h1>
			<%= @player.name %>
		</h1>
		<h3>
			ELO: <%= @player.elo %>
		</h3>
		<br>
		<br>
		<h3>
			Wins: <%= @player.wins.count %>
		</h3>
		<h3>
			Losses: <%= @player.lose.count%>
		</h3>
		<br>
		<br>
		<h4>
			Date Joined: <%= @player.created_at.to_date %>
		</h4>
	</div>
</div>
<div class = "games_holder_r">
	<div class = "left_head">
		<p class = "text_header">
			<%= @player.name %>'s Recent games
		</p>
	</div>
	<div class = "left">
		<table border = "1" class="table" style="text-align: center;">
			<tr>
				<th>Date</th>
				<th>Opponent</th>
				<th>Outcome</th>
				<th><%= @player.name %>'s Score</th>
				<th>Opponent's score</th>
			</tr>
			<% @player_games.each_with_index do |t, index| %>
				<tr>
					<td>
						<%= t.created_at.to_date %>
					</td>
					<td>
						<% if @wins.include?(t) %>
							<%= link_to t.loser.name, player_url(t.loser_id) %>
						<% else %>
							<%= link_to t.winner.name, player_url(t.winner_id) %>
						<% end %>
					</td>
					<% if @wins.include?(t)%>
						<td style="color: green">Win</td>
					<% else %>
						<td style = "color: red">Loss</td>
					<% end %>
					<td>
						<% if @wins.include?(t) %>
							<%= t.winner_score %>
						<% else %>
							<%= t.loser_score %>
						<% end %>
					</td>
					<td>
						<% if @wins.include?(t) %>
							<%= t.loser_score %>
						<% else %>
							<%= t.winner_score %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</table>
	</div>
</div>